server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    web-application-type: servlet

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


